### ISSUE TITLE
哪位大哥帮我看看这个该怎么解决呢

### ISSUE THREAD

**Issue by 1229984599** [aiyijing/familycloudaccelerate#10]
![image](https://user-images.githubusercontent.com/34052312/57007742-8dc72200-6c1d-11e9-8290-5100177317e4.png)

**Comment by chenxing2007** [comment]
查看这个参数channelId “qq”改成web

**Comment by 1229984599** [comment]
感谢解答啦，我这个参数就是用的这个。刚刚突然就又能用了，我感到很蒙蔽，虽然那个错误依旧在




------------------ 原始邮件 ------------------
发件人: "chenxing2007"<notifications@github.com>; 
发送时间: 2019年5月1日(星期三) 下午2:34
收件人: "aiyijing/familycloudaccelerate"<familycloudaccelerate@noreply.github.com>; 
抄送: "$a"<768091671@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [aiyijing/familycloudaccelerate] 哪位大哥帮我看看这个该怎么解决呢 (#10)




查看这个参数channelId “qq”改成web
