### ISSUE TITLE
请教python 2.7.15该如何修改

### ISSUE THREAD

**Issue by November-raining** [aiyijing/familycloudaccelerate#2]
路由器装的python 2.7.15。运行报错
Sending heart_beat package <1>
Traceback (most recent call last):
  File "/etc/1/1.py", line 96, in <module>
    send_data=send_data
  File "/etc/1/1.py", line 56, in heart_beat
    signature = get_signature(ACCESS_URL, session, secret, method, date)
  File "/etc/1/1.py", line 37, in get_signature
    return mac_sha1(params, session_secret)
  File "/etc/1/1.py", line 14, in mac_sha1
    key = bytes(secret, encoding='utf-8')
TypeError: str() takes at most 1 argument (2 given)
搜了下typeerror报错不知如何是好。。。

**Comment by aiyijing** [comment]
这个支持只支持Python3。如果你需要，明天我改个Python2.7的。把pipfreeze也写上。

**Comment by November-raining** [comment]
谢谢大佬😂😂，之前是直接抓包拖脚本，但是发现每次提速Signature不同，而且一定时间后脚本失灵得重新抓。看到那位大神blog才知是算出来的，感觉这种应该能挺的长一些。
而且我抓包看到sessionkey和sessionsecret有分个人和family两类的成对存在，还不知二者有何区别
