### ISSUE TITLE
好像不行，江苏电信

### ISSUE THREAD

**Issue by vcheckzen** [aiyijing/familycloudaccelerate#5]
```
$ python FamilySpeedUp.py
Sending heart_beat package <1>
heart_beat:<signature:C72000957F0BDB0AE15982EFF73D853E70036857>
date:<Wed, 17 Apr 2019 04:52:10 GMT>
status_code:400
response:
<?xml version="1.0" encoding="UTF-8"?>
<error><code>FamilyOperationFailed</code><message>open() - requestId=b7116f57-0753-42c3-8686-8844235496a4,sessionKey=XXXXXXXXXX,port=1509,clientIp=XXXXXXXXXX,dialAcct=js::XXXXXXXXXX,Family Operation Failed,580A12D48B6085A9A0B365231630AC1EDAD752BCC870BBBD73C708431951BBD56511BACE1A48DA90710228A320642EBFE0059B1D499B9869355103D98B666A1577E9CFE520EAD11,580A12D48B6085A9A0B365231630AC1EDAD752BCC870BBBD73C708431951BBD565114BACE1A48DA0710228A320642EBFE0059B1D499B9869355103D98B666A1577E9CFE520EAD11</message></error>
Send heart_beat <1> package Success
```

**Comment by chenxing2007** [comment]
在抓包软件提供查看一下这个链接的请求http://api.cloud.189.cn/family/qos/startQosaction?”

**Comment by chenxing2007** [comment]
查看一下"channelId": "web"这个参数是否和你抓住结果一致，抓包软件在这个请求里查找http://api.cloud.189.cn/family/qos/startQosaction?

**Comment by aiyijing** [comment]
@vcheckzen  那个哥们说的没错误
```shell
"send_data":{
          "prodCode": "76",     # 默认
          "version": "2.0.10",  # app 版本
          "channelId": "web"    # 默认参数
},
"extra_header":{
          "User-Agent": "Apache-HttpClient/UNAVAILABLE (java 1.4)"    #附加HTTP Header
}
```
这些字段都是预留出来的，都在http://api.cloud.189.cn/family/qos/startQosaction 这个包里面。要酌情修改，本人测试环境是安卓平台，不同登录方式，比如QQ 对应的channelid =qq。还有UA字段，如果是安卓，应该都是这个，如果是IOS的话，估计不一样。

**Comment by vcheckzen** [comment]
好的，虽然有错误，但还是提速了，我再抓包测试反馈，感谢解答

**Comment by aiyijing** [comment]
@vcheckzen  这个原理其实就是一直调用开始加速，所以余额分钟数都是不会减少的。由于已经加速了所以会返回那个FamilyOperationFailed。希望以后继续沟通。

**Comment by vcheckzen** [comment]
@aiyijing 嗯嗯，会的

**Comment by vcheckzen** [comment]
抓了好多次，不出现 `startQos` 的请求，关于 `qos` 只有两条，所以找不到 `prodCode`，`channelId` 是 `qq`，其他参数都是对的，但改了以后还是 `400` 请求，安卓系统
![Screenshot_2019-04-17-19-07-12-806_com guoshi htt](https://user-images.githubusercontent.com/18008498/56283399-34062880-6144-11e9-9598-77297e25b59b.png)

**Comment by chenxing2007** [comment]
是400说明就是正确的。软件返回也是400。

**Comment by lxxself** [comment]
![image](https://user-images.githubusercontent.com/8406766/56372276-44e09800-6231-11e9-8afa-d44cebf2106f.png)
这样是正常？

**Comment by vcheckzen** [comment]
正常
