### ISSUE TITLE
加速成功了，但是有一些困惑

### ISSUE THREAD

**Issue by sjlleo** [aiyijing/familycloudaccelerate#7]
在魔都地区，提速成功的返回代码甚至连我的宽带账号都会有。照理来说一个session应该对应的是一个宽带，但是同时我把我的提速session用到隔壁邻居家去，隔壁也能正常提速，不懂他们session认证的原理。

**Comment by chenxing2007** [comment]
家庭云账号和宽带账号不是绑定关系，家庭云APP本来就可以在任何电信宽带提速。你的发现又是一个好的思路了，感谢。

**Comment by sjlleo** [comment]
好像这种提速并不只是提升了宽带上传下载最高速率那么简单，我原日本NTT线路不装BBR/锐速连1080p都带不动，现在2K随便跑，加了BBR可以直接上4K，其他国外的VPS都有类似的加速效果，我猜应该是把宽带的出国QOS等级也提上去了，平均丢包率从原来23%降低到5%，神奇。

**Comment by chenxing2007** [comment]
这么玄学吗，魔都电信国际出口听说很坑。希望在多对比一下。

**Comment by sjlleo** [comment]
刚刚测的魔都电信不加任何加速 连接日本东京VPS 走NTT线路
是很坑 晚上出口不用各种加速3M都没有（我200M宽带）
现在这个点照理来说应该也只能勉强跑1080p 但是挂了这个脚本以后 就变成下图这样了
![image](https://user-images.githubusercontent.com/13616352/56345480-65d5c880-61f2-11e9-80c2-444dea14c235.png)

**Comment by BayMaxzhang001** [comment]
魔都晚上出口都给了vip，哈哈哈哈。限速是正常的。

**Comment by xinxin8816** [comment]
电信引以为傲的CN2 GIA和CN2 GT美洲方向的国际出口起点都是上海，也就是大半个中国都从上海出国。没有VIP加成的普通电信163线路用户就不要指望能看1080p了，通通要让路给CN2
